import React,{useEffect,useState} from 'react';
import {ShieldCheck,Play,Activity,Network,AlertTriangle,CheckCircle2,ChevronRight,LockKeyhole,RefreshCw,Upload,FileJson,Info} from 'lucide-react';
const API='http://localhost:8000/api';
function Metric({label,value,sub,icon:Icon}){return <div className="metric"><div className="metricIcon"><Icon size={18}/></div><div><div className="metricLabel">{label}</div><div className="metricValue">{value}</div><div className="metricSub">{sub}</div></div></div>}
function Check({label,ok}){return <div className="check"><span className={ok?'checkOk':'checkNo'}>{ok?<CheckCircle2 size={18}/>:<AlertTriangle size={18}/>}</span><span>{label}</span><b>{ok===null?'N/A':ok?'PASS':'REVIEW'}</b></div>}
function Graph({scenario,run}){
  const imported=run?.mode==='IMPORTED_IAM';
  const permissions=scenario?.permissions||[];
  const deps=scenario?.dependencies||[];
  const services=scenario?.services||[];
  return <section className="card graphCard"><div className="cardHead"><div><h2>Permission Evidence Graph</h2><p>{imported?'IAM configuration + audit/dependency evidence':'Permission → service dependency → operational evidence'}</p></div><span className="pill">{deps.length} edges</span></div>
    {imported?<div className="importGraph"><div className="node role">{scenario?.role||'Imported Role'}</div><div className="importPermGrid">{permissions.slice(0,24).map((p,i)=><div className="node permission" key={i}>{p}</div>)}</div>{deps.length?<div className="dependencyList"><b>Observed dependency edges</b>{deps.map((d,i)=><div className="dependencyRow" key={i}><span>{d.from||d.service||'Service'}</span><ChevronRight size={15}/><span>{d.to||d.permission||d.action||'Dependency'}</span>{d.label&&<small>{d.label}</small>}</div>)}</div>:<div className="graphNote"><Info size={16}/> No service/dependency telemetry was included in this import. Add dependency evidence to prove functionality relationships.</div>}{services.length>0&&<div className="dependencyList"><b>Service checks</b>{services.map((s,i)=><div className="dependencyRow" key={i}><span>{s.name}</span><ChevronRight size={15}/><span>{(s.required||[]).join(', ')||'No permissions listed'}</span><small>{s.critical?'CRITICAL':'CHECK'}</small></div>)}</div>}</div>:
    <div className="graph"><div className="node role">{scenario?.role||'Role'}</div><div className="node permission p1">s3:GetObject</div><div className="node permission p2">dynamodb:PutItem</div><div className="node permission p3">ec2:StartInstances</div><div className="node service s1">Payment Service</div><div className="node service s2">Auto Scaling</div><div className="evidence ev1">187 audit calls<br/><small>required dependency</small></div><div className="evidence ev2">3 calls / 8 days<br/><small>dependency retained</small></div></div>}
  </section>
}
function Policy({decisions,finalPolicy,imported}){return <section className="card"><div className="cardHead"><div><h2>Evidence-backed policy analysis</h2><p>{imported?'Decisions combine IAM configuration, audit usage and dependency evidence.':'Every change has a decision rationale.'}</p></div><span className="verified"><CheckCircle2 size={16}/> {imported?'ANALYZED':'VERIFIED'}</span></div><div className="table"><div className="tr th"><span>Permission</span><span>Decision</span><span>Evidence</span></div>{decisions.map((d,i)=><div className="tr" key={i}><span className="mono">{d.permission}{d.resource&&d.resource!=='*'?<small className="resource"> · {d.resource}</small>:null}</span><span className={'decision '+d.decision.toLowerCase()}>{d.decision}</span><span>{d.reason}</span></div>)}</div><div className="finalPolicy"><b>Recommended policy · {finalPolicy.length} permissions</b><code>{finalPolicy.join('  ·  ')}</code></div></section>}
function App(){
  const [scenarios,setScenarios]=useState([]),[scenario,setScenario]=useState('payment-role'),[run,setRun]=useState(null),[loading,setLoading]=useState(false),[tab,setTab]=useState('overview'),[mode,setMode]=useState('synthetic'),[file,setFile]=useState(null),[error,setError]=useState('');
  useEffect(()=>{fetch(API+'/scenarios').then(r=>r.json()).then(setScenarios).catch(()=>{})},[]);
  const execute=async()=>{setLoading(true);setRun(null);setError('');try{const r=await fetch(API+'/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario_id:scenario})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Run failed');setRun(data)}catch(e){setError(e.message||'Start the FastAPI backend on port 8000 first.')}finally{setLoading(false)}};
  const importJson=async()=>{if(!file){setError('Choose an IAM JSON export first.');return}setLoading(true);setRun(null);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch(API+'/analyze-upload',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not analyze the JSON');setRun(data);setTab('overview')}catch(e){setError(e.message||'Upload failed.')}finally{setLoading(false)}};
  const events=run?.events?.length?run.events:(run?.mode==='IMPORTED_IAM'?[{agent:'IAM Import Parser',role:'Detect provider and normalize IAM/RBAC JSON',message:`Parsed ${run.import_summary?.permission_count||0} permission entries.`,duration_ms:0},{agent:'IAM Forensics',role:'Classify privilege sensitivity and scope',message:`Found ${run.import_summary?.high_risk_permissions||0} high-risk permission(s).`,duration_ms:0},{agent:'Usage Intelligence',role:'Correlate audit evidence with configured access',message:`Audit evidence covers ${run.import_summary?.audit_entries_supplied||0} permission(s).`,duration_ms:0},{agent:'Dependency Intelligence',role:'Map permissions to service requirements',message:`Loaded ${run.import_summary?.dependencies_supplied||0} dependency edge(s) and ${run.import_summary?.services_supplied||0} service check(s).`,duration_ms:0},{agent:'Policy Strategist',role:'Generate evidence-backed least-privilege recommendations',message:`Generated ${run.import_summary?.removed_candidates||0} removal candidate(s).`,duration_ms:0},{agent:'Final Verifier',role:'Verify security, functionality and evidence coverage',message:`Final decision: ${run.verification?.status||'REVIEW'}.`,duration_ms:0}]:[]);
  const ver=run?.verification||{},sim=run?.simulation||{},decisions=run?.decisions||[],imported=run?.mode==='IMPORTED_IAM';
  return <div className="app"><header><div className="brand"><div className="brandMark"><ShieldCheck size={24}/></div><div><div className="brandName">AegisIAM</div><div className="brandTag">Autonomous Least-Privilege Security</div></div></div><div className="headerRight"><span className="statusDot"/> {imported?'Evidence Import':'Synthetic Cloud'} <span className="pill">SAFE SANDBOX</span></div></header><main>
    <section className="hero"><div><div className="eyebrow">MULTI-AGENT SECURITY ORCHESTRATOR</div><h1>Don't just remove permissions.<br/><span>Prove they can be removed.</span></h1><p>Evidence-driven IAM hardening with autonomous investigation, simulation, recovery and adversarial verification.</p></div>
      <div className="runBox"><label>Security mission</label><div className="modeSwitch"><button className={mode==='synthetic'?'selected':''} onClick={()=>{setMode('synthetic');setError('')}}>Synthetic scenario</button><button className={mode==='import'?'selected':''} onClick={()=>{setMode('import');setError('')}}><Upload size={15}/> Import IAM JSON</button></div>
      {mode==='synthetic'?<><select value={scenario} onChange={e=>setScenario(e.target.value)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={execute} disabled={loading}>{loading?<><RefreshCw className="spin" size={17}/> Running agents...</>:<><Play size={17}/> Start autonomous run</>}</button></>:<><label className="uploadLabel"><FileJson size={19}/><span>{file?file.name:'Choose IAM + evidence JSON'}</span><input type="file" accept=".json,application/json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button onClick={importJson} disabled={loading}>{loading?<><RefreshCw className="spin" size={17}/> Analyzing evidence...</>:<><Upload size={17}/> Analyze IAM JSON</>}</button><small className="helper">IAM-only exports are analysis-only. For full simulation, upload an evidence-enriched JSON containing usage, dependencies and service requirements.</small></>}
      {error&&<div className="errorBox"><AlertTriangle size={16}/>{error}</div>}</div>
    </section>
    {run&&<><div className="metrics"><Metric label="Security Score" value={ver.security_score??'—'} sub="risk analysis / 100" icon={ShieldCheck}/><Metric label="Functionality" value={ver.functionality_score??'N/A'} sub={imported?'service checks':'critical services'} icon={Activity}/><Metric label="Permissions Removed" value={ver.removed?.length??'—'} sub={imported?'evidence-backed':'evidence-backed'} icon={LockKeyhole}/><Metric label="Replans" value={run.replans?.length||run.iteration||0} sub={imported?'adaptive recovery':'adaptive cycles'} icon={RefreshCw}/></div>
      {imported&&<div className="notice"><Info size={17}/><div><b>{run.verification?.evidence_coverage==='GOOD'?'Evidence-enriched import':'IAM-only import'}</b><span>{run.verification?.evidence_coverage==='GOOD'?'AegisIAM used IAM + audit/dependency evidence. The proposed policy is tested in the local synthetic sandbox before verification.':'IAM JSON tells AegisIAM what access is configured, but cannot prove what is used. Add usage and dependency evidence to enable simulation and autonomous recovery.'}</span></div></div>}
      <nav className="tabs">{[['overview','Mission'],['agents','Agent Trace'],['graph','Evidence Graph'],['policy','Policy Diff']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
      {tab==='overview'&&<div className="grid2"><section className="card"><div className="cardHead"><div><h2>{imported?'Import analysis trace':'Autonomous execution'}</h2><p>{imported?'Goal → Parse → Analyze → Recommend → Simulate → Adapt → Verify':'Goal → Decision → Action → Observation → Adaptation → Verification'}</p></div><span className="verified">{run.status}</span></div><div className="timeline">{events.map((e,i)=><div className="event" key={i}><div className={'eventDot '+(e.agent==='Root Cause Agent'?'failure':'')}/><div className="eventBody"><div className="eventTop"><b>{e.agent}</b><span>{e.duration_ms} ms</span></div><div>{e.message}</div><small>{e.role}</small></div><ChevronRight size={16} className="chev"/></div>)}</div></section><section className="card"><div className="cardHead"><div><h2>Verification cockpit</h2><p>{imported?'Evidence + simulation checks':'Independent final checks'}</p></div></div><div className="checkList"><Check label="Critical services healthy" ok={imported?ver.services_healthy:ver.services_healthy}/><Check label="Least-privilege changes evidenced" ok={imported?ver.evidence_coverage==='GOOD':true}/><Check label="Red-team findings cleared" ok={ver.red_team_clean}/><Check label="Final policy simulated" ok={imported?sim.status==='PASS':sim.status==='PASS'}/></div><div className="resultBox"><div className="resultIcon"><ShieldCheck size={25}/></div><div><b>Final decision</b><strong>{ver.status||'PENDING'}</strong><span>{imported?(ver.status==='VERIFIED'?'Evidence-backed policy verified in the local sandbox.':'Analysis only — additional evidence or review is required.'):'Policy is approved only after simulation + red-team verification.'}</span></div></div></section></div>}
      {tab==='agents'&&<section className="card"><div className="cardHead"><div><h2>Agent trace</h2><p>Every analysis stage is visible and explainable.</p></div></div><div className="agentGrid">{events.map((e,i)=><div className="agentCard" key={i}><div className="agentBadge">{i+1}</div><div><b>{e.agent}</b><p>{e.role}</p><span className="agentMsg">{e.message}</span></div><span className="complete">DONE</span></div>)}</div></section>}
      {tab==='graph'&&<Graph scenario={run.scenario} run={run}/>} {tab==='policy'&&<Policy decisions={decisions} finalPolicy={run.proposed_policy||[]} imported={imported}/>}</>}
    {!run&&!loading&&<section className="empty"><div className="emptyIcon"><Network size={30}/></div><h2>{mode==='import'?'Ready to analyze your IAM evidence bundle':'Ready to harden your synthetic cloud'}</h2><p>{mode==='import'?'Upload IAM JSON alone for conservative analysis, or use an evidence-enriched JSON with usage, dependencies and service requirements for simulation + autonomous recovery.':'Select a scenario and launch the autonomous multi-agent mission. PaymentRole includes a deliberate failure so you can watch the system diagnose and replan.'}</p><div className="flow"><span>{mode==='import'?'Parse':'Investigate'}</span><ChevronRight/><span>Analyze</span><ChevronRight/><span>Recommend</span><ChevronRight/><span>Simulate</span><ChevronRight/><span>Verify</span></div></section>}
  </main><footer><span>AegisIAM · Tech Zephyr 4.0 · Problem 10</span><span>100% local simulation · No production credentials</span></footer></div>
}
export default App;
